name: Build and Deploy Vite App to Azure App Service (Docker)

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: react-vite-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A0BC88FFF6A343FAAE447BC24B8D0CA9 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF3E1A404C884D06942654C0A6361593 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CB62E06247BD4E73AC5E53E762C0EBCE }}

    - name: Login to ACR
      run: |
        docker login $ACR_LOGIN_SERVER \
        -u ${{ secrets.ACR_USERNAME }} \
        -p ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: webfr
        images: $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
